### ISSUE TITLE
What are these Equations?

### ISSUE THREAD

**Issue by allbluelai** [JiadingWen/01-Manipulator_Simulation#1]
There are many Equations in each .m file. 
Could you tell me what are these Equations?
Or where(Paper? Book? Reference?) can I found these Equations?
for example:
in "Manipulator_RoboticsToolBox\02 Simulation IBVS Monocular\Main.m"
```matlab
    % Get pixel coordinates of 4 interest points
    T_c_s = inv(T_s_e_current);  %equation 2.3
    m_c_i = Camera_3to2(X_s_i_set,T_c_s); %equation 2.4
```
I don't know all the Equations mean in .m file.

**Comment by JiadingWen** [comment]
You can search Pin-hole Camera model and Visual Servoing reference paper-"Visual Servo Control Part I: Basic Approaches BY FRANÇOIS CHAUMETTE AND SETH HUTCHINSON"

**Comment by allbluelai** [comment]
> You can search Pin-hole Camera model and Visual Servoing reference paper-"Visual Servo Control Part I: Basic Approaches BY FRANÇOIS CHAUMETTE AND SETH HUTCHINSON"

OK, thank you very much.
