### ISSUE TITLE
matlab vision servo is too slow

### ISSUE THREAD

**Issue by cd001100** [JiadingWen/01-Manipulator_Simulation#3]
Hello author, is there a problem of slowing down the real visual servo with matlab, how to control the angular velocity of the robot arm with matlab output from the visual servo, is there any way to control the robot arm, thanks

**Comment by JiadingWen** [comment]
I guess you want to limit the angular velocity?
To do that, for example, in "02 Simulation IBVS Monocular/Main.m":
`% Upper limit of angular velocity of robot manipulator joints (rad/s)`
`joint_velocity_max = 0.5;`
You can change the value of "joint_velocity_max" to limit the output (i.e. "theta_deria") of function "PUMA_ivkine".

By the way, the animation you saw from matlab is just a demenstration.
The trajectory of the arm in animation is reliable, but the velocity is not.
