### ISSUE TITLE
请问您的参考文献是什么，我注意到公式后面的标号

### ISSUE THREAD

**Issue by devilmaycry122** [JiadingWen/01-Manipulator_Simulation#4]

**Comment by JiadingWen** [comment]
You can search Pin-hole Camera model and Visual Servoing reference paper-"Visual Servo Control Part I: Basic Approaches BY FRANÇOIS CHAUMETTE AND SETH HUTCHINSON"

**Comment by lllzzzxxxccc** [comment]
Hello, is there any other reference, I found that this code does not exactly match the above reference, I am a student, I am learning related knowledge, some parts of the code are not well understood, can you send me the relevant literature? My email is 1980896734@qq.com, thank you very much！
